{% set name = "interegular" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/interegular-{{ version }}.tar.gz
  sha256: d9b697b21b34884711399ba0f0376914b81899ce670032486d0d048344a76600

build:
  skip: true # [ py<310 ]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - interegular
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/MegaIng/interegular
  summary: A regex intersection checker
  description: |
    A library to check a subset of python regexes for intersections. Based on
    greenery by @qntm. Adapted for lark-parser.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/MegaIng/interegular
  doc_url: https://github.com/MegaIng/interegular

extra:
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - pavelzw
